eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
   port: 8120
spring:
   application:
      name: service-feign
feign:
   hystrix:
      enabled: true
   service-helloworld:
      ribbon:
         NFLoadBalancerRuleClassName:com.netflix.loadbalance.RandomRule


